import { readFile, writeFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { transform } from '@svgr/core';
import { optimize } from 'svgo';

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const projectDirectory = dirname(scriptDirectory);
const manifestPath = join(projectDirectory, 'assets', 'icons', 'manifest.json');
const generatedDirectory = join(
  projectDirectory,
  'shared',
  'components',
  'icons',
  'generated',
);
const checkOnly = process.argv.includes('--check');

function componentNameFor(iconName) {
  return `${iconName.charAt(0).toUpperCase()}${iconName.slice(1)}Icon`;
}

function makeColorCustomizable(componentCode) {
  return componentCode
    .replaceAll('fill="var(--fill-0, white)"', "fill={props.color ?? '#FFFFFF'}")
    .replaceAll('fill="white"', "fill={props.color ?? '#FFFFFF'}");
}

async function writeGeneratedFile(filePath, contents) {
  if (checkOnly) {
    try {
      const existingContents = await readFile(filePath, 'utf8');
      if (existingContents === contents) return;
    } catch {
      // A missing generated file is handled by the same stale-output error.
    }

    throw new Error(`Generated icon is stale: ${filePath}`);
  }

  await writeFile(filePath, contents, 'utf8');
}

const manifest = JSON.parse(await readFile(manifestPath, 'utf8'));
const indexLines = ['// Generated by scripts/generate-icons.mjs. Do not edit manually.'];

for (const [iconName, definition] of Object.entries(manifest)) {
  const componentName = componentNameFor(iconName);
  const sourcePath = join(dirname(manifestPath), definition.source);
  const sourceSvg = await readFile(sourcePath, 'utf8');
  const optimizedSvg = optimize(sourceSvg, {
    multipass: true,
    plugins: [
      'preset-default',
      {
        name: 'removeDimensions',
        active: true,
      },
      {
        name: 'removeAttrs',
        params: { attrs: ['svg:style', 'svg:xmlns', 'svg:overflow'] },
      },
    ],
  }).data;
  const componentCode = makeColorCustomizable(
    await transform(
      optimizedSvg,
      {
        expandProps: 'end',
        icon: true,
        native: true,
        plugins: ['@svgr/plugin-jsx'],
        typescript: true,
      },
      { componentName },
    ),
  );

  await writeGeneratedFile(
    join(generatedDirectory, `${componentName}.tsx`),
    `// Generated by scripts/generate-icons.mjs. Do not edit manually.\n${componentCode}\n`,
  );
  indexLines.push(`export { default as ${componentName} } from './${componentName}';`);
}

await writeGeneratedFile(join(generatedDirectory, 'index.ts'), `${indexLines.join('\n')}\n`);
